name: musicp
description: The simple music player and finder, an app in Flutter.

version: 0.1.0

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^0.8.0+3
  google_sign_in: ^4.0.1
  cloud_firestore: ^0.9.0+1
  http: ^0.12.0+1
  path_provider: ^0.5.0+1
  audioplayers: ^0.10.0
  async: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true